require: rubocop-rspec

AllCops:
  Include:
    - '**/Rakefile'
    - '*.gemspec'
  Exclude:
    - 'pkg/**/*'

# These cops need to remain disabled for valid reasons on this code base

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

RSpec/ExampleLength:
  Max: 19

RSpec/MultipleExpectations:
  Enabled: false

Style/FileName:
  Exclude:
    - 'Gemfile'

# set_ methods are the part of PDF::Reader API
Style/AccessorMethodName:
  Enabled: false

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

# We need to reference non-ascii characters when testing and explaining
# behavior related to win-1252, UTF-8 and UTF-16 encodings for example.
Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/GuardClause:
  Enabled: false

# We don't always prefer modified if statements even if they do fit on
# a line.
Style/IfUnlessModifier:
  Enabled: false

Style/MultilineOperationIndentation:
  Exclude:
    - prawn.gemspec

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%': '()'
    '%i': '[]'
    '%I': '[]'
    '%q': '()'
    '%Q': '()'
    '%r': '{}'
    '%s': '()'
    '%w': '[]'
    '%W': '[]'
    '%x': '()'

Style/SymbolProc:
  Exclude:
    - 'spec/spec_helper.rb'

Style/WhileUntilModifier:
  Enabled: false
